FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json* ./

RUN npm install --production

COPY . .

RUN npx prisma generate

EXPOSE 5000

ENV PORT=5000
ENV REDIS_HOST=redis
ENV REDIS_PORT=6379

CMD ["node", "index.js"]
